<a href="https://colab.research.google.com/github/jermanalopes/MachineLearningBasic/blob/main/kNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix


In [67]:
# Database information and organize
base = pd.read_csv('mt_cars.csv')
x = base[['mpg', 'hp']].values
y = base['cyl'].values

In [68]:
# Training and Test data
x_training, x_test, y_training, y_test = train_test_split(x,y,test_size=0.3, random_state=1)


In [69]:
# KNN algorithm
knn = KNeighborsClassifier(n_neighbors=3)
model = knn.fit(x_training,y_training)
predict = model.predict(x_test)
print(predict)


[6 6 8 4 8 4 8 8 4 8]


In [70]:
# Metrics
acc = accuracy_score(y_test, predict)
precision = precision_score(y_test, predict, average='weighted')
recall = recall_score(y_test, predict, average='weighted')
f1 = f1_score(y_test, predict, average='weighted')
cmatrix = confusion_matrix(y_test, predict)
print(f'Acc: {acc}, Precision:{precision}, Recall: {recall}, f1:{f1}')
print('Confusion Matrix\n', cmatrix)



Acc: 0.9, Precision:0.95, Recall: 0.9, f1:0.9095238095238095
Confusion Matrix
 [[3 1 0]
 [0 1 0]
 [0 0 5]]


In [71]:
# Testing kNN algorithm with new data
# new_data = 'mpg', 'hp'
new_data = np.array([[19.3, 105]])
new_predict = model.predict(new_data)
print(f'The new predict is: {new_predict}')


The new predict is: [6]
[[1.2        4.5177428  5.28109837]]
[[21 15 11]]


5     6
31    4
1     6
Name: cyl, dtype: int64